### ISSUE TITLE
RU Team Cannot Capture E

### ISSUE THREAD

**Issue by LeonLionHeart** [Mobius1/MetroCQL#1]
E for the RU team is blocked from capturing the flag due to being out of the combat zone. 
[Image Capurte](https://i.imgur.com/ENtGxhL.jpg)

**Comment by Mobius1** [comment]
Fix incoming.

**Comment by Mobius1** [comment]
This is fixed in [v0.0.6](https://github.com/Mobius1/MetroCQL/releases/tag/0.0.6)
